language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t gdivino/react-docker-dev .
  # - docker run -e CI=true gdivino/frontend-dev yarn test

script:
  - docker run -e CI=true gdivino/react-docker-dev yarn test